/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ['./projects/**/*.html', './projects/**/*.ts', './projects/**/*.scss'],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        primary: {
          50: 'hsl(var(--color-primary-050) / <alpha-value>)',
          100: 'hsl(var(--color-primary-100) / <alpha-value>)',
          200: 'hsl(var(--color-primary-200) / <alpha-value>)',
          300: 'hsl(var(--color-primary-300) / <alpha-value>)',
          400: 'hsl(var(--color-primary-400) / <alpha-value>)',
          500: 'hsl(var(--color-primary-500) / <alpha-value>)',
          600: 'hsl(var(--color-primary-600) / <alpha-value>)',
          700: 'hsl(var(--color-primary-700) / <alpha-value>)',
          800: 'hsl(var(--color-primary-800) / <alpha-value>)',
          900: 'hsl(var(--color-primary-900) / <alpha-value>)',
        },
        test: {
          50: 'hsl(var(--color-test-050) / <alpha-value>)',
          100: 'hsl(var(--color-test-100) / <alpha-value>)',
          200: 'hsl(var(--color-test-200) / <alpha-value>)',
          300: 'hsl(var(--color-test-300) / <alpha-value>)',
          400: 'hsl(var(--color-test-400) / <alpha-value>)',
          500: 'hsl(var(--color-test-500) / <alpha-value>)',
          600: 'hsl(var(--color-test-600) / <alpha-value>)',
          700: 'hsl(var(--color-test-700) / <alpha-value>)',
          800: 'hsl(var(--color-test-800) / <alpha-value>)',
          900: 'hsl(var(--color-test-900) / <alpha-value>)',
        },
        neutral: {
          0: 'hsl(var(--color-neutral-000) / <alpha-value>)',
          50: 'hsl(var(--color-neutral-050) / <alpha-value>)',
          100: 'hsl(var(--color-neutral-100) / <alpha-value>)',
          200: 'hsl(var(--color-neutral-200) / <alpha-value>)',
          300: 'hsl(var(--color-neutral-300) / <alpha-value>)',
          400: 'hsl(var(--color-neutral-400) / <alpha-value>)',
          500: 'hsl(var(--color-neutral-500) / <alpha-value>)',
          600: 'hsl(var(--color-neutral-600) / <alpha-value>)',
          700: 'hsl(var(--color-neutral-700) / <alpha-value>)',
          800: 'hsl(var(--color-neutral-800) / <alpha-value>)',
          900: 'hsl(var(--color-neutral-900) / <alpha-value>)',
        },
        risk: {
          50: 'hsl(var(--color-risk-050) / <alpha-value>)',
          100: 'hsl(var(--color-risk-100) / <alpha-value>)',
          200: 'hsl(var(--color-risk-200) / <alpha-value>)',
          300: 'hsl(var(--color-risk-300) / <alpha-value>)',
          400: 'hsl(var(--color-risk-400) / <alpha-value>)',
          500: 'hsl(var(--color-risk-500) / <alpha-value>)',
          600: 'hsl(var(--color-risk-600) / <alpha-value>)',
          700: 'hsl(var(--color-risk-700) / <alpha-value>)',
          800: 'hsl(var(--color-risk-800) / <alpha-value>)',
          900: 'hsl(var(--color-risk-900) / <alpha-value>)',
        },
        warning: {
          50: 'hsl(var(--color-warning-050) / <alpha-value>)',
          100: 'hsl(var(--color-warning-100) / <alpha-value>)',
          200: 'hsl(var(--color-warning-200) / <alpha-value>)',
          300: 'hsl(var(--color-warning-300) / <alpha-value>)',
          400: 'hsl(var(--color-warning-400) / <alpha-value>)',
          500: 'hsl(var(--color-warning-500) / <alpha-value>)',
          600: 'hsl(var(--color-warning-600) / <alpha-value>)',
          700: 'hsl(var(--color-warning-700) / <alpha-value>)',
          800: 'hsl(var(--color-warning-800) / <alpha-value>)',
          900: 'hsl(var(--color-warning-900) / <alpha-value>)',
        },
        success: {
          50: 'hsl(var(--color-success-050) / <alpha-value>)',
          100: 'hsl(var(--color-success-100) / <alpha-value>)',
          200: 'hsl(var(--color-success-200) / <alpha-value>)',
          300: 'hsl(var(--color-success-300) / <alpha-value>)',
          400: 'hsl(var(--color-success-400) / <alpha-value>)',
          500: 'hsl(var(--color-success-500) / <alpha-value>)',
          600: 'hsl(var(--color-success-600) / <alpha-value>)',
          700: 'hsl(var(--color-success-700) / <alpha-value>)',
          800: 'hsl(var(--color-success-800) / <alpha-value>)',
          900: 'hsl(var(--color-success-900) / <alpha-value>)',
        },
        info: {
          50: 'hsl(var(--color-info-050) / <alpha-value>)',
          100: 'hsl(var(--color-info-100) / <alpha-value>)',
          200: 'hsl(var(--color-info-200) / <alpha-value>)',
          300: 'hsl(var(--color-info-300) / <alpha-value>)',
          400: 'hsl(var(--color-info-400) / <alpha-value>)',
          500: 'hsl(var(--color-info-500) / <alpha-value>)',
          600: 'hsl(var(--color-info-600) / <alpha-value>)',
          700: 'hsl(var(--color-info-700) / <alpha-value>)',
          800: 'hsl(var(--color-info-800) / <alpha-value>)',
          900: 'hsl(var(--color-info-900) / <alpha-value>)',
        },
        secondary: {
          50: 'hsl(var(--color-secondary-050) / <alpha-value>)',
          100: 'hsl(var(--color-secondary-100) / <alpha-value>)',
          200: 'hsl(var(--color-secondary-200) / <alpha-value>)',
          300: 'hsl(var(--color-secondary-300) / <alpha-value>)',
          400: 'hsl(var(--color-secondary-400) / <alpha-value>)',
          500: 'hsl(var(--color-secondary-500) / <alpha-value>)',
          600: 'hsl(var(--color-secondary-600) / <alpha-value>)',
          700: 'hsl(var(--color-secondary-700) / <alpha-value>)',
          800: 'hsl(var(--color-secondary-800) / <alpha-value>)',
          900: 'hsl(var(--color-secondary-900) / <alpha-value>)',
        },
      },
      textColor: {
        neutral: {
          0: 'hsl(var(--color-text-000) / <alpha-value>)',
          50: 'hsl(var(--color-text-050) / <alpha-value>)',
          100: 'hsl(var(--color-text-100) / <alpha-value>)',
          200: 'hsl(var(--color-text-200) / <alpha-value>)',
          300: 'hsl(var(--color-text-300) / <alpha-value>)',
          400: 'hsl(var(--color-text-400) / <alpha-value>)',
          500: 'hsl(var(--color-text-500) / <alpha-value>)',
          600: 'hsl(var(--color-text-600) / <alpha-value>)',
          700: 'hsl(var(--color-text-700) / <alpha-value>)',
          800: 'hsl(var(--color-text-800) / <alpha-value>)',
          900: 'hsl(var(--color-text-900) / <alpha-value>)',
        },
      },
      // backgroundOpacity: {
      opacity: {
        2.5: '0.025',
      },
      fontFamily: {
        sans: ['Roboto', 'sans-serif'],
      },
      fontSize: {
        xs: ['var(--font-size-xs)', { lineHeight: 'var(--font-size-xs-line-height)' }],
        sm: ['var(--font-size-sm)', { lineHeight: 'var(--font-size-sm-line-height)' }],
        base: ['var(--font-size-base)', { lineHeight: 'var(--font-size-base-line-height)' }],
        md: ['var(--font-size-md)', { lineHeight: 'var(--font-size-md-line-height)' }],
        lg: ['var(--font-size-lg)', { lineHeight: 'var(--font-size-lg-line-height)' }],
        xl: ['var(--font-size-xl)', { lineHeight: 'var(--font-size-xl-line-height)' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--font-size-2xl-line-height)' }],
        '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--font-size-3xl-line-height)' }],
        '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--font-size-4xl-line-height)' }],
        '4.5xl': ['var(--font-size-4_5xl)', { lineHeight: 'var(--font-size-4_5xl-line-height)' }],
        '5xl': ['var(--font-size-5xl)', { lineHeight: 'var(--font-size-5xl-line-height)' }],
        '6xl': ['var(--font-size-6xl)', { lineHeight: 'var(--font-size-6xl-line-height)' }],
        '7xl': ['var(--font-size-7xl)', { lineHeight: 'var(--font-size-7xl-line-height)' }],
        '8xl': ['var(--font-size-8xl)', { lineHeight: 'var(--font-size-8xl-line-height)' }],
        '9xl': ['var(--font-size-9xl)', { lineHeight: 'var(--font-size-9xl-line-height)' }],
        'static-xs': ['var(--font-size-static-xs)', { lineHeight: 'var(--font-size-static-xs-line-height)' }],
        'static-sm': ['var(--font-size-static-sm)', { lineHeight: 'var(--font-size-static-sm-line-height)' }],
        'static-base': ['var(--font-size-static-base)', { lineHeight: 'var(--font-size-static-base-line-height)' }],
        'static-md': ['var(--font-size-static-md)', { lineHeight: 'var(--font-size-static-md-line-height)' }],
        'static-lg': ['var(--font-size-static-lg)', { lineHeight: 'var(--font-size-static-lg-line-height)' }],
        'static-xl': ['var(--font-size-static-xl)', { lineHeight: 'var(--font-size-static-xl-line-height)' }],
        'static-2xl': ['var(--font-size-static-2xl)', { lineHeight: 'var(--font-size-static-2xl-line-height)' }],
        'static-3xl': ['var(--font-size-static-3xl)', { lineHeight: 'var(--font-size-static-3xl-line-height)' }],
        'static-4xl': ['var(--font-size-static-4xl)', { lineHeight: 'var(--font-size-static-4xl-line-height)' }],
        'static-4.5xl': ['var(--font-size-static-4_5xl)', { lineHeight: 'var(--font-size-static-4_5xl-line-height)' }],
        'static-5xl': ['var(--font-size-static-5xl)', { lineHeight: 'var(--font-size-static-5xl-line-height)' }],
        'static-6xl': ['var(--font-size-static-6xl)', { lineHeight: 'var(--font-size-static-6xl-line-height)' }],
        'static-7xl': ['var(--font-size-static-7xl)', { lineHeight: 'var(--font-size-static-7xl-line-height)' }],
        'static-8xl': ['var(--font-size-static-8xl)', { lineHeight: 'var(--font-size-static-8xl-line-height)' }],
        'static-9xl': ['var(--font-size-static-9xl)', { lineHeight: 'var(--font-size-static-9xl-line-height)' }],
      },
      gridTemplateRows: {
        7: 'repeat(7, minmax(0, 1fr))',
        8: 'repeat(8, minmax(0, 1fr))',
        9: 'repeat(9, minmax(0, 1fr))',
        10: 'repeat(10, minmax(0, 1fr))',
        11: 'repeat(11, minmax(0, 1fr))',
        12: 'repeat(12, minmax(0, 1fr))',
        13: 'repeat(13, minmax(0, 1fr))',
        14: 'repeat(14, minmax(0, 1fr))',
        15: 'repeat(15, minmax(0, 1fr))',
        16: 'repeat(16, minmax(0, 1fr))',
        17: 'repeat(17, minmax(0, 1fr))',
        18: 'repeat(18, minmax(0, 1fr))',
        19: 'repeat(19, minmax(0, 1fr))',
        20: 'repeat(20, minmax(0, 1fr))',
        21: 'repeat(21, minmax(0, 1fr))',
        22: 'repeat(22, minmax(0, 1fr))',
        23: 'repeat(23, minmax(0, 1fr))',
        24: 'repeat(24, minmax(0, 1fr))',
      },
      minHeight: (theme) => ({
        ...theme('spacing'),
      }),
      minWidth: (theme) => ({
        ...theme('spacing'),
      }),
    },
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      mdl: '900px',
      table: '960px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
  },
  plugins: [
    require('@tailwindcss/forms')({
      strategy: 'base',
    }),
    require('@tailwindcss/container-queries'),
  ],
};
