package lt.project.ntis.dao;

import lt.project.ntis.dao.gen.NtisWastewaterTreatmentFaciDAOGen;
import java.util.Date;

public class NtisWastewaterTreatmentFaciDAO extends NtisWastewaterTreatmentFaciDAOGen {
   public NtisWastewaterTreatmentFaciDAO() {
      super();
   }
   public NtisWastewaterTreatmentFaciDAO(Double wtf_id, String wtf_manufacturer, String wtf_manufacturer_description, String wtf_model, String wtf_type, String wtf_capacity, Double wtf_distance, String wtf_technical_passport_id, String wtf_state, String wtf_data_source, Date wtf_installation_date, Date wtf_checkout_date, String wtf_deleted, Double wtf_facility_latitude, Double wtf_facility_longitude, String wtf_facility_municipality_code, String wtf_discharge_type, Double wtf_discharge_latitude, Double wtf_discharge_longitude, Double wtf_ad_id, Double wtf_agg_id, String wtf_waiting_update_confirmation, Double wtf_nc_ad_id, Double wtf_nc_agg_id, String wtf_nc_manufacturer, String wtf_nc_manufacturer_description, String wtf_nc_model, String wtf_nc_type, String wtf_nc_capacity, Double wtf_nc_distance, String wtf_nc_technical_passport_id, String wtf_nc_data_source, Date wtf_nc_installation_date, Date wtf_nc_checkout_date, String wtf_nc_deleted, Double wtf_nc_facility_latitude, Double wtf_nc_facility_longitude, String wtf_nc_facility_municipality_code, String wtf_nc_discharge_type, Double wtf_nc_discharge_latitude, Double wtf_nc_discharge_longitude, Double rec_version, Date rec_create_timestamp, String rec_userid, Date rec_timestamp, Double n01, Double n02, Double n03, Double n04, Double n05, String c01, String c02, String c03, String c04, String c05, Date d01, Date d02, Date d03, Date d04, Date d05, Double wtf_fam_id, Double wtf_nc_fam_pop_equivalent, String wtf_nc_fam_tech_pass, Double wtf_nc_fam_chds, Double wtf_nc_fam_bds, Double wtf_nc_fam_float_material, Double wtf_nc_fam_phosphor, Double wtf_nc_fam_nitrogen, String wtf_nc_fam_manufacturer, String wtf_nc_fam_model, String wtf_nc_fam_description) {
      super(wtf_id, wtf_manufacturer, wtf_manufacturer_description, wtf_model, wtf_type, wtf_capacity, wtf_distance, wtf_technical_passport_id, wtf_state, wtf_data_source, wtf_installation_date, wtf_checkout_date, wtf_deleted, wtf_facility_latitude, wtf_facility_longitude, wtf_facility_municipality_code, wtf_discharge_type, wtf_discharge_latitude, wtf_discharge_longitude, wtf_ad_id, wtf_agg_id, wtf_waiting_update_confirmation, wtf_nc_ad_id, wtf_nc_agg_id, wtf_nc_manufacturer, wtf_nc_manufacturer_description, wtf_nc_model, wtf_nc_type, wtf_nc_capacity, wtf_nc_distance, wtf_nc_technical_passport_id, wtf_nc_data_source, wtf_nc_installation_date, wtf_nc_checkout_date, wtf_nc_deleted, wtf_nc_facility_latitude, wtf_nc_facility_longitude, wtf_nc_facility_municipality_code, wtf_nc_discharge_type, wtf_nc_discharge_latitude, wtf_nc_discharge_longitude, rec_version, rec_create_timestamp, rec_userid, rec_timestamp, n01, n02, n03, n04, n05, c01, c02, c03, c04, c05, d01, d02, d03, d04, d05, wtf_fam_id, wtf_nc_fam_pop_equivalent, wtf_nc_fam_tech_pass, wtf_nc_fam_chds, wtf_nc_fam_bds, wtf_nc_fam_float_material, wtf_nc_fam_phosphor, wtf_nc_fam_nitrogen, wtf_nc_fam_manufacturer, wtf_nc_fam_model, wtf_nc_fam_description);
   }
}