package lt.project.ntis.dao;

import lt.project.ntis.dao.gen.NtisOrderFileDataDAOGen;
import java.util.Date;

public class NtisOrderFileDataDAO extends NtisOrderFileDataDAOGen {
   public NtisOrderFileDataDAO() {
      super();
   }
   public NtisOrderFileDataDAO(Double orfd_id, Double orfd_eil_nr, Double orfd_wtf_id, Double orfd_orf_id, Double orfd_org_id, String orfd_paslaugos_kodas, String orfd_pastato_kodas, String orfd_patalpos_kodas, String orfd_pastato_adr_kodas, String orfd_adresas, String orfd_savivaldybes_kodas, String orfd_savivaldybe, String orfd_seniunijos_kodas, String orfd_seniunija, String orfd_gyv_vietos_kodas, String orfd_gyv_vieta, String orfd_gatves_kodas, String orfd_gatve, String orfd_pastato_nr, String orfd_korpuso_nr, String orfd_buto_nr, String orfd_paslauga, String orfd_uzsakymo_data, String orfd_atlikimo_data, String orfd_isvezimo_data, String orfd_isveztas_kiekis, String orfd_transporto_priemone, Double orfd_cr_id, String orfd_uzsakymo_informacija, String orfd_atlikti_darbai, String orfd_uzsakovas, String orfd_uzsakovo_email, String orfd_uzsakovo_tel, String orfd_uzsakovo_komentaras, String orfd_laboratorijos_komentaras, String orfd_deguonis, String orfd_skendincios, String orfd_azotas, String orfd_fosforas, String orfd_meginio_data, String orfd_meginio_darbuotojas, String orfd_tyrimo_data, String orfd_tyrimo_darbuotojas, String orfd_pastaba_rezultatams, Double rec_version, Date rec_create_timestamp, String rec_userid, Date rec_timestamp, Double n01, Double n02, Double n03, Double n04, Double n05, String c01, String c02, String c03, String c04, String c05, Date d01, Date d02, Date d03, Date d04, Date d05) {
      super(orfd_id, orfd_eil_nr, orfd_wtf_id, orfd_orf_id, orfd_org_id, orfd_paslaugos_kodas, orfd_pastato_kodas, orfd_patalpos_kodas, orfd_pastato_adr_kodas, orfd_adresas, orfd_savivaldybes_kodas, orfd_savivaldybe, orfd_seniunijos_kodas, orfd_seniunija, orfd_gyv_vietos_kodas, orfd_gyv_vieta, orfd_gatves_kodas, orfd_gatve, orfd_pastato_nr, orfd_korpuso_nr, orfd_buto_nr, orfd_paslauga, orfd_uzsakymo_data, orfd_atlikimo_data, orfd_isvezimo_data, orfd_isveztas_kiekis, orfd_transporto_priemone, orfd_cr_id, orfd_uzsakymo_informacija, orfd_atlikti_darbai, orfd_uzsakovas, orfd_uzsakovo_email, orfd_uzsakovo_tel, orfd_uzsakovo_komentaras, orfd_laboratorijos_komentaras, orfd_deguonis, orfd_skendincios, orfd_azotas, orfd_fosforas, orfd_meginio_data, orfd_meginio_darbuotojas, orfd_tyrimo_data, orfd_tyrimo_darbuotojas, orfd_pastaba_rezultatams, rec_version, rec_create_timestamp, rec_userid, rec_timestamp, n01, n02, n03, n04, n05, c01, c02, c03, c04, c05, d01, d02, d03, d04, d05);
   }
}