export interface ServedObjectsView {
  bn_ad_id: number;
  fua_id: number;
  bn_aob_code: number;
  bn_construction_completion: number;
  bn_construction_end_year: number;
  bn_construction_start_year: number;
  bn_coordinate_latitude_adr: number;
  bn_coordinate_latitude_ntr: number | null;
  bn_coordinate_longitude_adr: number;
  bn_coordinate_longitude_ntr: number | null;
  bn_declr_type: string;
  bn_flat_nr: string;
  bn_full_address: string;
  bn_house_nr: string;
  bn_housing_nr: string;
  bn_id: number;
  bn_live_count: number;
  bn_living_area: number;
  bn_municipality: string;
  bn_municipality_code: string;
  bn_obj_inv_code: string;
  bn_obj_inv_parent_code: string;
  bn_object_inv_date: string;
  bn_object_name: string;
  bn_object_type: number;
  bn_pask_name: string;
  bn_pask_type: number;
  bn_place_code: string;
  bn_place_name: string;
  bn_reg_nr: string;
  bn_sen_code: string;
  bn_sen_name: string;
  bn_status: string;
  bn_status_desc: string;
  bn_street: string;
  bn_street_code: string;
  bn_total_area: number;
  bn_useable_area: number;
  bn_wastewater_treatment: string;
  bn_water_supply: string;
  ntr_owner: string;
  org_name: string;
  org_code: string;
  ba_network_connection_date: string;
  ba_network_disconnection_date: string;
  cwfd_atjungimo_data: Date;
  cwf_import_date: Date;
  cwf_updated_at: Date;
  ba_wastewater_treatment: string;
  ba_wastewater_treatment_clsf: string;
  so_id: number;
  so_created: Date;
  so_updated: Date;
  so_updated_by: string;
  bn_created: Date;
  org_name_m: string;
  ba_wastewater_treatment_m: string;
  ba_network_connection_date_m: string;
  ba_state: string;
  wtf_files_json: string;
}

export interface NtrOwners {
  bno_name: string;
  bno_lastname: string;
  bno_org_name: string;
  bno_code: string;
}
