export enum UserType {
  PRIVATE_USER = 'PRIVATE',
  ORGANIZATION_USER = 'ORGANIZATION',
  PRIVATE_ORG = 'PRIVATE_ORG',
}

export enum AuthType {
  USER_PASSWORD_AUTH = 'USER_PASSWORD_AUTH',
  VIISP_AUTH = 'VIISP_AUTH',
}
