// NTIS_AGLO_STATUS
export const NTIS_AGLO_STATUS = 'NTIS_AGLO_STATUS';
export const AGLO_STATUS_CHECKING = 'AGLO_STATUS_CHECKING';
export const AGLO_STATUS_APPROVED = 'AGLO_STATUS_APPROVED';
export const AGLO_STATUS_REJECTED = 'AGLO_STATUS_REJECTED';

// NTIS_SRV_ITEM_TYPE
export const NTIS_SRV_ITEM_TYPE = 'NTIS_SRV_ITEM_TYPE';
export const PRIEZIURA = 'PRIEZIURA';
export const TYRIMAI = 'TYRIMAI';
export const VALYMAS = 'VALYMAS';
export const VEZIMAS = 'VEZIMAS';
export const MONTAVIMAS = 'MONTAVIMAS';

// NTIS_WTF_TYPE
export const NTIS_WTF_TYPE = 'NTIS_WTF_TYPE';

// NTIS_MUNICIPALITIES
export const NTIS_MUNICIPALITIES = 'NTIS_MUNICIPALITIES';

// NTIS_ORDER_STATUS
export const NTIS_ORDER_STATUS = 'NTIS_ORDER_STATUS';
export const ORD_STS_SUBMITTED = 'ORD_STS_SUBMITTED';
export const ORD_STS_CANCELLED = 'ORD_STS_CANCELLED';
export const ORD_STS_REJECTED = 'ORD_STS_REJECTED';
export const ORD_STS_CONFIRMED = 'ORD_STS_CONFIRMED';
export const ORD_STS_FINISHED = 'ORD_STS_FINISHED';

// NTIS_SRV_PRVD_STATE
export const SRV_PRVD_DEREGISTERED = 'SRV_PRVD_DEREGISTERED';
export const SRV_PRVD_REGISTERED = 'SRV_PRVD_REGISTERED';
export const SRV_PRVD_INACTIVE = 'SRV_PRVD_DEREGISTERED';
export const SRV_PRVD_DEREGISTERED_VALUE = 'Išregistruotas';
export const SRV_PRVD_REGISTERED_VALUE = 'Užregistruotas';

// SLUDGE_DELIVERY_INFO
export const SLD_DLV_WHOLE = 'SLD_DLV_WHOLE';
export const SLD_DLV_PARTIAL = 'SLD_DLV_PARTIAL';
export const SLD_DLV_USED = 'SLD_DLV_USED';

// SEWAGE_TYPE
export const SWG_TYP_DOMESTIC = 'SWG_TYP_DOMESTIC';
export const SWG_TYP_INDUSTRIAL = 'SWG_TYP_INDUSTRIAL';
export const SWG_TYP_SLUDGE = 'SWG_TYP_SLUDGE';

// SEWAGE_DELIV_STATUS
export const SEWAGE_DELIV_STATUS = 'SEWAGE_DELIV_STATUS';
export const SWG_DLV_STS_SUBMITTED = 'SWG_DLV_STS_SUBMITTED';
export const SWG_DLV_STS_REJECTED = 'SWG_DLV_STS_REJECTED';
export const SWG_DLV_STS_CONFIRMED = 'SWG_DLV_STS_CONFIRMED';
export const SWG_DLV_STS_USED = 'SWG_DLV_STS_CONFIRMED';

// SERVICE_STATUS;
export const SERVICE_STATUS = 'SERVICE_STATUS';
export const SRV_STS_INACTIVE = 'SRV_STS_INACTIVE';
export const SRV_STS_ACTIVE = 'SRV_STS_ACTIVE';
export const SRV_STS_SUSPENDED = 'SRV_STS_SUSPENDED';

// WTF_STATE
export const REGISTERED = 'REGISTERED';
export const CONFIRMED = 'CONFIRMED';
export const CLOSED = 'CLOSED';

// FACILITY UPDATE REQUEST STATUS
export const REQ_STS_CONFIRMED = 'REQ_STS_CONFIRMED';
export const UNCONFIRMED = 'UNCONFIRMED';

// NTIS_COT_STATE
export const NTIS_COT_STATE = 'NTIS_COT_STATE';
