/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ['./lib/**/*.html', './lib/**/*.ts', './lib/**/*.scss'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'hsl(var(--s2-color-primary-050) / <alpha-value>)',
          100: 'hsl(var(--s2-color-primary-100) / <alpha-value>)',
          200: 'hsl(var(--s2-color-primary-200) / <alpha-value>)',
          300: 'hsl(var(--s2-color-primary-300) / <alpha-value>)',
          400: 'hsl(var(--s2-color-primary-400) / <alpha-value>)',
          500: 'hsl(var(--s2-color-primary-500) / <alpha-value>)',
          600: 'hsl(var(--s2-color-primary-600) / <alpha-value>)',
          700: 'hsl(var(--s2-color-primary-700) / <alpha-value>)',
          800: 'hsl(var(--s2-color-primary-800) / <alpha-value>)',
          900: 'hsl(var(--s2-color-primary-900) / <alpha-value>)',
        },
        neutral: {
          0: 'hsl(var(--s2-color-neutral-000) / <alpha-value>)',
          50: 'hsl(var(--s2-color-neutral-050) / <alpha-value>)',
          100: 'hsl(var(--s2-color-neutral-100) / <alpha-value>)',
          200: 'hsl(var(--s2-color-neutral-200) / <alpha-value>)',
          300: 'hsl(var(--s2-color-neutral-300) / <alpha-value>)',
          400: 'hsl(var(--s2-color-neutral-400) / <alpha-value>)',
          500: 'hsl(var(--s2-color-neutral-500) / <alpha-value>)',
          600: 'hsl(var(--s2-color-neutral-600) / <alpha-value>)',
          700: 'hsl(var(--s2-color-neutral-700) / <alpha-value>)',
          800: 'hsl(var(--s2-color-neutral-800) / <alpha-value>)',
          900: 'hsl(var(--s2-color-neutral-900) / <alpha-value>)',
        },
        risk: {
          50: 'hsl(var(--s2-color-risk-050) / <alpha-value>)',
          100: 'hsl(var(--s2-color-risk-100) / <alpha-value>)',
          200: 'hsl(var(--s2-color-risk-200) / <alpha-value>)',
          300: 'hsl(var(--s2-color-risk-300) / <alpha-value>)',
          400: 'hsl(var(--s2-color-risk-400) / <alpha-value>)',
          500: 'hsl(var(--s2-color-risk-500) / <alpha-value>)',
          600: 'hsl(var(--s2-color-risk-600) / <alpha-value>)',
          700: 'hsl(var(--s2-color-risk-700) / <alpha-value>)',
          800: 'hsl(var(--s2-color-risk-800) / <alpha-value>)',
          900: 'hsl(var(--s2-color-risk-900) / <alpha-value>)',
        },
        warning: {
          50: 'hsl(var(--s2-color-warning-050) / <alpha-value>)',
          100: 'hsl(var(--s2-color-warning-100) / <alpha-value>)',
          200: 'hsl(var(--s2-color-warning-200) / <alpha-value>)',
          300: 'hsl(var(--s2-color-warning-300) / <alpha-value>)',
          400: 'hsl(var(--s2-color-warning-400) / <alpha-value>)',
          500: 'hsl(var(--s2-color-warning-500) / <alpha-value>)',
          600: 'hsl(var(--s2-color-warning-600) / <alpha-value>)',
          700: 'hsl(var(--s2-color-warning-700) / <alpha-value>)',
          800: 'hsl(var(--s2-color-warning-800) / <alpha-value>)',
          900: 'hsl(var(--s2-color-warning-900) / <alpha-value>)',
        },
        success: {
          50: 'hsl(var(--s2-color-success-050) / <alpha-value>)',
          100: 'hsl(var(--s2-color-success-100) / <alpha-value>)',
          200: 'hsl(var(--s2-color-success-200) / <alpha-value>)',
          300: 'hsl(var(--s2-color-success-300) / <alpha-value>)',
          400: 'hsl(var(--s2-color-success-400) / <alpha-value>)',
          500: 'hsl(var(--s2-color-success-500) / <alpha-value>)',
          600: 'hsl(var(--s2-color-success-600) / <alpha-value>)',
          700: 'hsl(var(--s2-color-success-700) / <alpha-value>)',
          800: 'hsl(var(--s2-color-success-800) / <alpha-value>)',
          900: 'hsl(var(--s2-color-success-900) / <alpha-value>)',
        },
        info: {
          50: 'hsl(var(--s2-color-info-050) / <alpha-value>)',
          100: 'hsl(var(--s2-color-info-100) / <alpha-value>)',
          200: 'hsl(var(--s2-color-info-200) / <alpha-value>)',
          300: 'hsl(var(--s2-color-info-300) / <alpha-value>)',
          400: 'hsl(var(--s2-color-info-400) / <alpha-value>)',
          500: 'hsl(var(--s2-color-info-500) / <alpha-value>)',
          600: 'hsl(var(--s2-color-info-600) / <alpha-value>)',
          700: 'hsl(var(--s2-color-info-700) / <alpha-value>)',
          800: 'hsl(var(--s2-color-info-800) / <alpha-value>)',
          900: 'hsl(var(--s2-color-info-900) / <alpha-value>)',
        },
      },
      textColor: {
        neutral: {
          0: 'hsl(var(--s2-color-text-000) / <alpha-value>)',
          50: 'hsl(var(--s2-color-text-050) / <alpha-value>)',
          100: 'hsl(var(--s2-color-text-100) / <alpha-value>)',
          200: 'hsl(var(--s2-color-text-200) / <alpha-value>)',
          300: 'hsl(var(--s2-color-text-300) / <alpha-value>)',
          400: 'hsl(var(--s2-color-text-400) / <alpha-value>)',
          500: 'hsl(var(--s2-color-text-500) / <alpha-value>)',
          600: 'hsl(var(--s2-color-text-600) / <alpha-value>)',
          700: 'hsl(var(--s2-color-text-700) / <alpha-value>)',
          800: 'hsl(var(--s2-color-text-800) / <alpha-value>)',
          900: 'hsl(var(--s2-color-text-900) / <alpha-value>)',
        },
      },
      fontSize: {
        xs: ['var(--s2-font-size-xs)', { lineHeight: 'var(--s2-font-size-xs-line-height)' }],
        sm: ['var(--s2-font-size-sm)', { lineHeight: 'var(--s2-font-size-sm-line-height)' }],
        base: ['var(--s2-font-size-base)', { lineHeight: 'var(--s2-font-size-base-line-height)' }],
        md: ['var(--s2-font-size-md)', { lineHeight: 'var(--s2-font-size-md-line-height)' }],
        lg: ['var(--s2-font-size-lg)', { lineHeight: 'var(--s2-font-size-lg-line-height)' }],
        xl: ['var(--s2-font-size-xl)', { lineHeight: 'var(--s2-font-size-xl-line-height)' }],
        '2xl': ['var(--s2-font-size-2xl)', { lineHeight: 'var(--s2-font-size-2xl-line-height)' }],
        '3xl': ['var(--s2-font-size-3xl)', { lineHeight: 'var(--s2-font-size-3xl-line-height)' }],
        '4xl': ['var(--s2-font-size-4xl)', { lineHeight: 'var(--s2-font-size-4xl-line-height)' }],
        '5xl': ['var(--s2-font-size-5xl)', { lineHeight: 'var(--s2-font-size-5xl-line-height)' }],
        '6xl': ['var(--s2-font-size-6xl)', { lineHeight: 'var(--s2-font-size-6xl-line-height)' }],
        '7xl': ['var(--s2-font-size-7xl)', { lineHeight: 'var(--s2-font-size-7xl-line-height)' }],
        '8xl': ['var(--s2-font-size-8xl)', { lineHeight: 'var(--s2-font-size-8xl-line-height)' }],
        '9xl': ['var(--s2-font-size-9xl)', { lineHeight: 'var(--s2-font-size-9xl-line-height)' }],
      },
      minHeight: (theme) => ({
        ...theme('spacing'),
      }),
      minWidth: (theme) => ({
        ...theme('spacing'),
      }),
    },
    screens: {
      xs: 'var(--s2-screen-xs)',
      sm: 'var(--s2-screen-sm)',
      md: 'var(--s2-screen-md)',
      mdl: 'var(--s2-screen-mdl)',
      lg: 'var(--s2-screen-lg)',
      xl: 'var(--s2-screen-xl)',
      '2xl': 'var(--s2-screen-2xl)',
    },
  },
  plugins: [
    require('@tailwindcss/forms')({
      strategy: 'base',
    }),
    require('@tailwindcss/container-queries'),
  ],
};
