
package lt.project.ntis.brokerws.get;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetPortType", targetNamespace = "http://www.registrucentras.lt")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({ ObjectFactory.class })
public interface GetPortType {

    /**
     * 
     * @param input
     * @return
     *     returns lt.registrucentras.GetResponseType
      */
    @WebMethod(operationName = "GetData", action = "urn:http://www.registrucentras.lt#get")
    @WebResult(partName = "return")
    public GetResponseType getData(@WebParam(name = "input", partName = "input") InputParams input);

    /**
     * 
     * @param input
     * @return
     *     returns lt.registrucentras.GetRcResponseType
     */
    @WebMethod(operationName = "GetDataRc", action = "urn:http://www.registrucentras.lt#get")
    @WebResult(partName = "return")
    public GetRcResponseType getDataRc(@WebParam(name = "input", partName = "input") InputParams input);

}
