//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 03:51:32 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.epaslaugos.lt/services/payment", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
		@jakarta.xml.bind.annotation.XmlNs(prefix = "payment", namespaceURI = "http://www.epaslaugos.lt/services/payment"),
		@jakarta.xml.bind.annotation.XmlNs(prefix = "dsig", namespaceURI = "http://www.w3.org/2000/09/xmldsig#") })
package lt.atea.vaiisis.payment.model.xml;
