//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 03:51:32 PM EET 
//


package lt.atea.vaiisis.payment.model.xml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Payment request message
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pid" type="{http://www.epaslaugos.lt/services/payment}pidType"/>
 *         &lt;element name="senderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="returnUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="webServiceUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="amount" type="{http://www.epaslaugos.lt/services/payment}money" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://www.epaslaugos.lt/services/payment}currency" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.epaslaugos.lt/services/payment}language" minOccurs="0"/>
 *         &lt;element name="message" type="{http://www.epaslaugos.lt/services/payment}message" minOccurs="0"/>
 *         &lt;element name="paymentCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="correlation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="thirdParty" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="payerCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="personFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="personLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="vendorRegNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="companyVatCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="paymentCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pid",
    "senderId",
    "returnUrl",
    "webServiceUrl",
    "amount",
    "currency",
    "language",
    "message",
    "paymentCode",
    "date",
    "correlation",
    "thirdParty",
    "signature"
})
@XmlRootElement(name = "paymentRequest", namespace = "http://www.epaslaugos.lt/services/payment")
public class PaymentRequestXml {

    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment", required = true)
    protected String pid;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment", required = true)
    protected String senderId;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String returnUrl;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
    @XmlSchemaType(name = "anyURI")
    protected String webServiceUrl;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
    protected BigDecimal amount;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
    protected Currency currency;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
    protected Language language;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
    protected String message;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
    protected String paymentCode;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
    protected String correlation;
    @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
    protected PaymentRequestXml.ThirdParty thirdParty;
    @XmlElement(name = "Signature", required = true)
    protected SignatureType signature;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the pid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPid() {
        return pid;
    }

    /**
     * Sets the value of the pid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPid(String value) {
        this.pid = value;
    }

    /**
     * Gets the value of the senderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * Sets the value of the senderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderId(String value) {
        this.senderId = value;
    }

    /**
     * Gets the value of the returnUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * Sets the value of the returnUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnUrl(String value) {
        this.returnUrl = value;
    }

    /**
     * Gets the value of the webServiceUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebServiceUrl() {
        return webServiceUrl;
    }

    /**
     * Sets the value of the webServiceUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebServiceUrl(String value) {
        this.webServiceUrl = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setCurrency(Currency value) {
        this.currency = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link Language }
     *     
     */
    public Language getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link Language }
     *     
     */
    public void setLanguage(Language value) {
        this.language = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the paymentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentCode() {
        return paymentCode;
    }

    /**
     * Sets the value of the paymentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentCode(String value) {
        this.paymentCode = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the correlation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelation() {
        return correlation;
    }

    /**
     * Sets the value of the correlation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelation(String value) {
        this.correlation = value;
    }

    /**
     * Gets the value of the thirdParty property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentRequestXml.ThirdParty }
     *     
     */
    public PaymentRequestXml.ThirdParty getThirdParty() {
        return thirdParty;
    }

    /**
     * Sets the value of the thirdParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentRequestXml.ThirdParty }
     *     
     */
    public void setThirdParty(PaymentRequestXml.ThirdParty value) {
        this.thirdParty = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="payerCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="personFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="personLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="vendorRegNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="companyVatCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="paymentCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "payerCode",
        "personFirstName",
        "personLastName",
        "companyName",
        "companyCode",
        "vendorRegNo",
        "companyVatCode",
        "paymentCode"
    })
    public static class ThirdParty {

        @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
        protected String payerCode;
        @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
        protected String personFirstName;
        @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
        protected String personLastName;
        @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
        protected String companyName;
        @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
        protected String companyCode;
        @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
        protected String vendorRegNo;
        @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
        protected String companyVatCode;
        @XmlElement(namespace = "http://www.epaslaugos.lt/services/payment")
        protected String paymentCode;

        /**
         * Gets the value of the payerCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPayerCode() {
            return payerCode;
        }

        /**
         * Sets the value of the payerCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPayerCode(String value) {
            this.payerCode = value;
        }

        /**
         * Gets the value of the personFirstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonFirstName() {
            return personFirstName;
        }

        /**
         * Sets the value of the personFirstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonFirstName(String value) {
            this.personFirstName = value;
        }

        /**
         * Gets the value of the personLastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonLastName() {
            return personLastName;
        }

        /**
         * Sets the value of the personLastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonLastName(String value) {
            this.personLastName = value;
        }

        /**
         * Gets the value of the companyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyName() {
            return companyName;
        }

        /**
         * Sets the value of the companyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyName(String value) {
            this.companyName = value;
        }

        /**
         * Gets the value of the companyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyCode() {
            return companyCode;
        }

        /**
         * Sets the value of the companyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyCode(String value) {
            this.companyCode = value;
        }

        /**
         * Gets the value of the vendorRegNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVendorRegNo() {
            return vendorRegNo;
        }

        /**
         * Sets the value of the vendorRegNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVendorRegNo(String value) {
            this.vendorRegNo = value;
        }

        /**
         * Gets the value of the companyVatCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyVatCode() {
            return companyVatCode;
        }

        /**
         * Sets the value of the companyVatCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyVatCode(String value) {
            this.companyVatCode = value;
        }

        /**
         * Gets the value of the paymentCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentCode() {
            return paymentCode;
        }

        /**
         * Sets the value of the paymentCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentCode(String value) {
            this.paymentCode = value;
        }

    }

}
