import { Injectable } from '@angular/core';
import {
  faNewspaper,
  faBell as farBell,
  faBellSlash as farBellSlash,
  faClock as farClock,
  faCircleXmark as farFaCircleXmark,
  faComment as farFaComment,
  faEnvelope as farFaEnvelope,
  faTrashCan as farFaTrashCan,
  faUser as farFaUser,
  faFileLines as farFileLines,
  faMessage as farMessage,
  faStar as farStar,
} from '@fortawesome/free-regular-svg-icons';
import {
  IconDefinition,
  faAddressBook,
  faAdjust,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faArrowCircleLeft,
  faArrowCircleRight,
  faArrowDownLong,
  faArrowLeft,
  faArrowRight,
  faArrowUpFromBracket,
  faArrowUpLong,
  faArrowUpRightFromSquare,
  faArrowsSpin,
  faAsterisk,
  faBan,
  faBars,
  faBorderAll,
  faBorderNone,
  faBox,
  faBriefcase,
  faBroom,
  faBuilding,
  faBuildingCircleArrowRight,
  faBuildingColumns,
  faCalendar,
  faCalendarCheck,
  faCalendarDays,
  faCheck,
  faCheckCircle,
  faCheckToSlot,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleCheck,
  faCircleInfo,
  faCirclePlus,
  faCircleQuestion,
  faCircleXmark,
  faCity,
  faClipboardList,
  faClockRotateLeft,
  faClone,
  faCog,
  faCogs,
  faCommentDots,
  faCopy,
  faDatabase,
  faDoorOpen,
  faDownLeftAndUpRightToCenter,
  faDownload,
  faDroplet,
  faEdit,
  faEllipsisH,
  faEllipsisV,
  faEnvelope,
  faEnvelopeOpen,
  faEnvelopesBulk,
  faExpand,
  faEye,
  faEyeSlash,
  faFile,
  faFileArrowDown,
  faFileArrowUp,
  faFileCircleXmark,
  faFileCsv,
  faFileExport,
  faFileInvoice,
  faFileLines,
  faFilePdf,
  faFilter,
  faFilterCircleXmark,
  faGripLines,
  faHandHoldingDroplet,
  faHeart,
  faHome,
  faHouse,
  faHouseFlag,
  faIdCard,
  faIndustry,
  faInfo,
  faInfoCircle,
  faKey,
  faLandmark,
  faLayerGroup,
  faLink,
  faList,
  faListCheck,
  faLocationCrosshairs,
  faLocationDot,
  faLongArrowAltLeft,
  faMap,
  faMapLocationDot,
  faMapMarkerAlt,
  faMinus,
  faMousePointer,
  faPalette,
  faPaperclip,
  faPencil,
  faPencilRuler,
  faPlus,
  faPrint,
  faQuestion,
  faQuestionCircle,
  faRecycle,
  faRedo,
  faSave,
  faSearch,
  faShieldAlt,
  faShieldHalved,
  faSignInAlt,
  faSignOutAlt,
  faSortAmountDown,
  faSortAmountUpAlt,
  faSpellCheck,
  faSpinner,
  faSquarePlus,
  faStar,
  faSync,
  faTable,
  faTableList,
  faTasks,
  faTextHeight,
  faTimes,
  faTimesCircle,
  faToggleOff,
  faToggleOn,
  faToolbox,
  faTools,
  faTrash,
  faTrashCan,
  faTree,
  faTriangleExclamation,
  faTruck,
  faTruckArrowRight,
  faTruckDroplet,
  faTruckField,
  faTruckRampBox,
  faUniversalAccess,
  faUpRightAndDownLeftFromCenter,
  faUpload,
  faUser,
  faUserAlt,
  faUserCheck,
  faUserCircle,
  faUserCog,
  faUserGear,
  faUserGroup,
  faUserPlus,
  faUserSlash,
  faUserTag,
  faUserTie,
  faUserXmark,
  faVial,
  faWater,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

@Injectable({
  providedIn: 'root',
})
export class FaIconsService {
  fab: Record<string, IconDefinition> = {};

  far: Record<string, IconDefinition> = {
    faBell: farBell,
    faBellSlash: farBellSlash,
    faCircleXmark: farFaCircleXmark,
    faClock: farClock,
    faComment: farFaComment,
    faEnvelope: farFaEnvelope,
    faFileLines: farFileLines,
    faMessage: farMessage,
    faTrashCan: farFaTrashCan,
    faUser: farFaUser,
    faStar: farStar,
  };

  fas: Record<string, IconDefinition> = {
    faAdjust,
    faAddressBook,
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faAngleUp,
    faArrowCircleLeft,
    faArrowCircleRight,
    faArrowDownLong,
    faArrowLeft,
    faArrowRight,
    faArrowsSpin,
    faArrowUpLong,
    faArrowUpFromBracket,
    faArrowUpRightFromSquare,
    faAsterisk,
    faBan,
    faBars,
    faBorderAll,
    faBorderNone,
    faBox,
    faBriefcase,
    faBroom,
    faBuilding,
    faBuildingCircleArrowRight,
    faBuildingColumns,
    faCalendar,
    faCalendarCheck,
    faCalendarDays,
    faCheck,
    faCheckCircle,
    faCheckToSlot,
    faChevronDown,
    faChevronUp,
    faChevronRight,
    faCircle,
    faCircleCheck,
    faCircleInfo,
    faCirclePlus,
    faCircleQuestion,
    faQuestion,
    faCircleXmark,
    faCity,
    faClipboardList,
    faClockRotateLeft,
    faClone,
    faCog,
    faCogs,
    faCommentDots,
    faCopy,
    faDatabase,
    faDoorOpen,
    faDownLeftAndUpRightToCenter,
    faDownload,
    faDroplet,
    faEdit,
    faEllipsisH,
    faEllipsisV,
    faEnvelope,
    faEnvelopeOpen,
    faEnvelopesBulk,
    faExpand,
    faEye,
    faEyeSlash,
    faFile,
    faFileCircleXmark,
    faFileCsv,
    faFileExport,
    faFileInvoice,
    faFileLines,
    faFilePdf,
    faFilter,
    faFilterCircleXmark,
    faFileArrowDown,
    faFileArrowUp,
    faGripLines,
    faHandHoldingDroplet,
    faHeart,
    faHome,
    faHouse,
    faHouseFlag,
    faIdCard,
    faIndustry,
    faInfo,
    faInfoCircle,
    faKey,
    faLandmark,
    faLayerGroup,
    faLink,
    faList,
    faListCheck,
    faLocationCrosshairs,
    faLocationDot,
    faLongArrowAltLeft,
    faMap,
    faMapLocationDot,
    faMapMarkerAlt,
    faMinus,
    faMousePointer,
    faNewspaper,
    faPalette,
    faPaperclip,
    faPencil,
    faPencilRuler,
    faPlus,
    faPrint,
    faQuestionCircle,
    faRecycle,
    faRedo,
    faSave,
    faSearch,
    faShieldAlt,
    faShieldHalved,
    faSignInAlt,
    faSignOutAlt,
    faSortAmountDown,
    faSortAmountUpAlt,
    faSpellCheck,
    faSpinner,
    faSquarePlus,
    faStar,
    faSync,
    faTable,
    faTableList,
    faTasks,
    faTextHeight,
    faTimes,
    faTimesCircle,
    faToggleOff,
    faToggleOn,
    faToolbox,
    faTools,
    faTrash,
    faTrashCan,
    faTree,
    faTriangleExclamation,
    faTruck,
    faTruckArrowRight,
    faTruckDroplet,
    faTruckField,
    faTruckRampBox,
    faUniversalAccess,
    faUpRightAndDownLeftFromCenter,
    faUpload,
    faUser,
    faUserAlt,
    faUserCheck,
    faUserCircle,
    faUserCog,
    faUserGear,
    faUserGroup,
    faUserPlus,
    faUserSlash,
    faUserTag,
    faUserTie,
    faUserXmark,
    faVial,
    faXmark,
    faWater,
  };

  brands: Record<string, IconDefinition> = this.fab;
  regular: Record<string, IconDefinition> = this.far;
  solid: Record<string, IconDefinition> = this.fas;
}
