name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:

permissions: { }

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    container: node:18
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @angular/cli
      - name: Link ng-s2-commons
        run: npm link
        working-directory: libs/ngx-s2-commons
      - name: Link ngx-s2-ui
        run: npm link
        working-directory: libs/ngx-s2-ui
      - name: Install dependencies
        run: |
          npm ci
          npm link @itree/ngx-s2-commons @itree/ngx-s2-ui
        working-directory: ntis-web
      - name: Build
        run: ng build itree-web
        working-directory: ntis-web
